### ISSUE TITLE
A way to avoid the -90 deg rotation?

### ISSUE THREAD

**Issue by fracteed** [Kupoman/blendergltf#106]
I am testing this plugin to get models into Godot3. they are coming in fine, but are parented under a null that has a -90deg rotation on the x-axis. I realise this is to change it to orientate it to be y-up, but this is not a good way to do it if you plan on further animating the meshes in other hierarchies, etc. Is there a planned way to avoid this in future, so that meshes come in with all zeroed out orientations?

**Comment by Kupoman** [comment]
That is currently the only option. Our intent was to add more options if there was a need for them. I'll add this issue to the road map for the next release, and we can begin discussing what another option or options would look like.

There are a few additional ways I can see applying the axis conversion:
1. Apply the axis transform to every node
2. Apply the axis transform to the mesh
3. Add the axis transform to the Blender object's transform, and then apply all of that to the mesh
4. Transform the root node, and then apply parent transforms through the hierarchy to nodes or meshes

Option 1 would be easy to add, but it sounds like that would not be very helpful to you. It sounds like you want all transforms applied to the mesh. Since Blender has various options to apply transforms, I believe a user could accomplish something like options 3 and 4 as long as option 2 was available. To me option 2 is looking to be the best return on investment of these options.

**Comment by fracteed** [comment]
Thanks for your detailed reply and for adding this to the roadmap! I am not too sure about the implications of all of these options, so I would trust your judgement that no.2 is the way to go. I often save a .mesh file from Godot (its native format) and after bringing in a scene using your exporter, these meshes are saved with the wrong orientation, which is an problem.

 If the transform has been applied to the mesh (ala option 2) I would assume that these meshes have zeroed out rotations but would be orientated as they were in Blender? Also, not sure what the implications are for meshes that have have a non-zeroed out rotation in the original Blender scene. If these are exported, will the orientations stay the same but translated to y-up?

I am sure that Blender having only z-up is a real pain for you guys doing the exporter. I had always hoped that it would eventually be added a y-up option, as it is one of the only applications that uses z-up. According to Campbell(blender dev) it will never happen, which is a shame...

**Comment by Kupoman** [comment]
I have started experimenting with one approach to solving this problem in the apply_axis branch. Skinned meshes are currently broken in that branch. Applying the axis conversion will eventually be an option, but it is always enabled in that branch for now. This means you should not have to change any settings to try it. I would appreciate it if you could give the branch a try to see if that behavior is closer to what you are expecting.

**Comment by fracteed** [comment]
@Kupoman sorry for the slow reply...just had a chance to try this. Yes, this is working well, cheers! I exported a few test objects using y/up -z forward from 2.79 into current Godot 3 branch and all worked well. Will continue to do some more tests as I have a few more issues that I have found. Thanks for adding this :)

**Comment by Kupoman** [comment]
Thank you for the feedback! I am glad to hear it is working well for you. I will get to work sorting out the problems with skinned meshes, and then start cleaning up the branch for merging into master.

**Comment by Kupoman** [comment]
After a long delay, this feature is finally in master! I am sure there will still be some bugs from it, but my initial tests with morph targets and skeletal animations were promising. The old behavior of adding a transformed root node has been replaced with this new behavior, so no additional options are needed to apply the transform.

Specific bugs from the new behavior can be addressed in new issues.

**Comment by fracteed** [comment]
Nice one, thanks!
