### ISSUE TITLE
The shape key animation on exported model is not working

### ISSUE THREAD

**Issue by artemistint** [Kupoman/blendergltf#118]
Is it supported? Any special setting for that?

**Comment by Kupoman** [comment]
Sorry, I somehow missed this issue getting posted. Support for morph targets was added by bf0d4af55926f46ca132b5c21ca08567c3dcbd99, and there have been a few fixes for them since then. You do not need to change any settings to use them. Can you elaborate on what problems you are having and provide a .blend file that is not exporting correctly?

**Comment by apostololeg** [comment]
Hi, i have the same problem, when trying export scene with animated meshes:
![2018-01-22_16-25-39](https://user-images.githubusercontent.com/514713/35223214-90a4e560-ff91-11e7-885a-9ca20c545cf5.png)

Source: [monkey.blend](https://file.io/YVKacy)
Exporter params:
![2018-01-22_16-31-47](https://user-images.githubusercontent.com/514713/35223281-cf8b24c4-ff91-11e7-876e-ba64c620568a.png)

_I'd appreciate for quick response._

**Comment by Kupoman** [comment]
Shape keys should be working better now. Thanks for reporting the problem.

**Comment by apostololeg** [comment]
Thanks for quick response!
Error not throwing now.

But shape keys animations has not exported. In fact, monkey.gltf contain no field "animation".
I've opened new issue for it https://github.com/Kupoman/blendergltf/issues/122.
