### ISSUE TITLE
Unused/hidden meshes

### ISSUE THREAD

**Issue by yrns** [Kupoman/blendergltf#37]
Meshes are still exported even if they are unused or used by hidden objects (not in nodes). I would sumbit a PR but maybe I'm missing something.

**Comment by stevenvergenz** [comment]
So the "Export Hidden Objects" flag is not respected?

**Comment by Kupoman** [comment]
I have not investigate this yet, but I am guessing it is a consequence of blendergltf being initially developed for the [Blender Real Time Engine Addon (usually just called brte)](https://github.com/Kupoman/BlenderRealtimeEngineAddon).  For that project, scene deltas are sent as glTF data to an external engine based on what Blender reports as having changed. When changing an object's visibility, Blender just reports the object as being changed. This means brte will send a new glTF node when an object becomes visible, but, if the mesh was pruned in the initial sending of data due to the node not being visible, then the mesh the node references will not be available on the external engine.

All that being said, I think we may want to be more aggressive at pruning unused data in blendergltf, and just work out these issues in brte. However, I first need to make sure I can properly detect cases like this in brte.

**Comment by stevenvergenz** [comment]
I'll work on this. All the extra objects that aren't my model in the glTF have always bugged me :)

**Comment by Kupoman** [comment]
Like I said earlier, this is more or less work as intended in order to make things easier for BRTE. Before we change this behavior, BRTE needs to be updated to be smarter about handling visibility updates.

**Comment by stevenvergenz** [comment]
Oh, is this still used by BRTE? I thought it was forked off.

**Comment by Kupoman** [comment]
I think as long as we can keep the old behavior as a setting, we can maintain compatibility with BRTE. My suggestion is to add a setting ("gltf_prune_unused" should work for a name) that, when enabled, will attempt to only export data that is considered to be in use. This should default to false in blendergltf.py for now. The addon can always set this to true since I don't think it is worth exposing the setting in the UI.

**Comment by stevenvergenz** [comment]
That's a good idea about the hidden settings! I'll get started on this soon. While we're at it, would you mind if the "Export Actions"/"Export Physics Settings" options were hidden too? These are non-standard extensions, and I don't think anything but BRTE uses them.

**Comment by Moguri** [comment]
I am okay with hiding Export Actions when we deprecate BLENDER_actions, but I would like to keep the option to export BLENDER_physics exposed. After BLENDER_physics is stable, documented, and tested, I plan to submit it as a vendor extension to the glTF Extension Registry.

**Comment by Kupoman** [comment]
With the merging of pull request #56, this should now be working better.
