### ISSUE TITLE
Clean up settings UI

### ISSUE THREAD

**Issue by Kupoman** [Kupoman/blendergltf#46]
Right now everything is kind of thrown in at random, and few things actually have tool tips. It would also be nice to group some of the settings like the COLLADA exporter does.

**Comment by stevenvergenz** [comment]
I've looked into this a bit, and I'm not sure we'll be able to implement nice grouped settings like the Collada exporter does. It seems the Collada exporter is written in C++, presumably before the Python interface was implemented. I haven't found any other exporters that make use of grouped settings, so who knows.

This exporter will have 16 settings once my PRs are merged, which seems excessive to me:
* **Up axis** - necessary
* **Forward axis** - necessary
* **Selection only** - necessary
* **Interleave vertex data** - necessary. Support isn't 100% yet
* **Image storage** - necessary, though I think "reference" should be the default, not "copy"
* **Embed buffer data** - useful. Though will be redundant after gltf_binary is implemented
* **Shader storage** - useful
* **Export hidden objects** - useful
* **Pretty-print JSON** - useful
* **Combine buffer data** - not necessary. When would you ever want separate buffers?
* **Prune unused resources** - not necessary
* **Apply modifiers** - not necessary. When would this ever be false?
* **sRGB texture support** - unknown. What percentage of consumer applications support sRGB?
* **glTF profile**- not necessary. There are no other profile types listed in the spec.
* **Export physics** - unknown. How many consumers care about blender physics?
* **Export actions** - not useful, until animations are supported

**Comment by Moguri** [comment]
@stevenvergenz 
My thoughts on a few of the points:

* Embed buffer data - if/when blendergltf supports binary glTF, we'll still want the option to export non-binary glTF
* Combine buffer data - this is useful for streaming glTF since you can open multiple connections to get buffer data
* Prune unused resources - I thought we weren't adding this to the UI?
* Apply modifiers - most Blender exporters expose such an option, but not sure if we really need to
* sRGB texture support - used by [BlenderPanda](https://github.com/Moguri/BlenderPanda), and is necessary for PBR workflows
* glTF profile - glTF currently only targets web, but Blender wants to target desktop OpenGL as well (e.g., with brte and BlenderPanda). However, the addon may not need to expose this.
* Export physics - Once I have the spec written up for this, I plan to add it to the [glTF extension registry](https://github.com/KhronosGroup/glTF/tree/master/extensions)
* Export actions - This currently exports BLENDER_actions animations. We'd like to drop this extension and move toward only supporting core animations. However, we'll still likely want an option to control animation/action export.

**Comment by stevenvergenz** [comment]
> should be guarded by a setting #56

**Comment by Moguri** [comment]
I think @Kupoman may have been referring to a module setting, but we can have the addon always set this to True without exposing UI. However, I'll let @Kupoman comment on that. I am in favor of not exposing a UI option for this.

**Comment by Kupoman** [comment]
Sorry, I was a bit unclear there. I was referring to only having a setting for the module, not the addon.

**Comment by Kupoman** [comment]
Found a way to add custom drawing code! I did some initial grouping and organization in 1a4a5ee.

**Comment by stevenvergenz** [comment]
It looks good! The only thing I would ask for would be collapsible panels, but that's optional IMHO.
